import { Product } from "./types";

export const products: Product[] = [
    {
      id: 1,
      title: "Stylish Cotton T-Shirt",
      image: ["/picture/top-4.png"],
      slug: "stylish-cotton-tshirt",
      price: 100,
      discount: 10,
      category: "tops",
      description: "A comfortable and stylish cotton t-shirt perfect for casual outings.",
      size: ["M", "L", "XL"],
      color: ["#fff", "#800000", "#e06000"],
      qty: 1,
    },
    {
      id: 2,
      title: "Premium Leather Wallet",
      image: ["/picture/top-9.png"],
      slug: "premium-leather-wallet",
      price: 2500,
      discount: 15,
      category: "Accessories",
      description: "A premium leather wallet with multiple compartments for convenience.",
      size: [],
      color: ["#337357", "#FFA447"],
      qty: 100,
    },
    {
      id: 3,
      title: "Running Shoes",
      image: ["/picture/top-8.png"],
      slug: "running-shoes",
      price: 5000,
      discount: 0,
      category: "tops",
      description: "Lightweight running shoes designed for comfort and performance.",
      size: ["7", "8", "9", "10", "11"],
      color: ["#0A97B0", "#8174A0", "#441752"],
      qty: 30,
    },
    {
      id: 4,
      title: "Smartphone",
      image: ["/picture/top-3.png"],
      slug: "tops",
      price: 80000,
      discount: 5,
      category: "pants",
      description: "A feature-packed smartphone with a stunning display and powerful processor.",
      size: [],
      color: ["#AA5486", "#4B4376"],
      qty: 20,
    },
    {
      id: 5,
      title: "Classic Denim Jeans",
      image: ["/picture/top-5.png"],
      slug: "classic-denim-jeans",
      price: 3000,
      discount: 0,
      category: "shoes",
      description: "Classic denim jeans that never go out of style.",
      size: ["28", "30", "32", "34", "36"],
      color: ["#FF2929", "#3B1C32"],
      qty: 40,
    },
    {
      id: 6,
      title: "Wireless Headphones",
      image: ["/picture/top-4.png"],
      slug: "wireless-headphones",
      price: 10000,
      discount: 25,
      category: "shoes",
      description: "High-quality wireless headphones with noise cancellation and long battery life.",
      size: [],
      color: ["#FF4545", "#FFE31A", "#3D0301"],
      qty: 15,
    },
  ];
  